imports:
    - { resource: parameters.ini }
    - { resource: security.yml }

framework:
    #esi:             ~
    translator:      { fallback: %locale% }
    secret:          %secret%
    charset:         UTF-8
    router:          { resource: "%kernel.root_dir%/config/routing.yml" }
    form:            true
    csrf_protection: true
    validation:      { enable_annotations: true }
    templating:      { engines: ['twig'] } #assets_version: SomeVersionScheme
    session:
        default_locale: %locale%
        auto_start:     true

# Twig Configuration
twig:
    debug:            %kernel.debug%
    strict_variables: %kernel.debug%

# Assetic Configuration
assetic:
    debug:          %kernel.debug%
    use_controller: false
    # java: /usr/bin/java
    filters:
        cssrewrite: ~
        # closure:
        #     jar: %kernel.root_dir%/java/compiler.jar
        # yui_css:
        #     jar: %kernel.root_dir%/java/yuicompressor-2.4.2.jar

# Doctrine Configuration
doctrine:
    dbal:
        driver:   %database_driver%
        host:     %database_host%
        port:     %database_port%
        dbname:   %database_name%
        user:     %database_user%
        password: %database_password%
        charset:  UTF8

    orm:
        auto_generate_proxy_classes: %kernel.debug%
        auto_mapping: true

# Swiftmailer Configuration
swiftmailer:
    transport: %mailer_transport%
    host:      %mailer_host%
    username:  %mailer_user%
    password:  %mailer_password%




services:
    weo.bancobundle.admin.tipocuenta:
        class: Weo\BancoBundle\Admin\TipoCuentaAdmin
        tags:
            - { name: sonata.admin, manager_type: orm, group: "Contabilidad Domestica", label: "Tipo cuenta" }
        arguments: [null, Weo\BancoBundle\Entity\TipoCuenta, WeoBancoBundle:TipoCuentaAdmin]
    weo.bancobundle.admin.tipoapunte:
        class: Weo\BancoBundle\Admin\TipoApunteAdmin
        tags:
            - { name: sonata.admin, manager_type: orm, group: "Contabilidad Domestica", label: "Tipo apunte" }
        arguments: [null, Weo\BancoBundle\Entity\TipoApunte, WeoBancoBundle:TipoApunteAdmin]
    weo.bancobundle.admin.entidadbanco:
        class:        Weo\BancoBundle\Admin\EntidadBancoAdmin
        tags:
          - { name: sonata.admin, manager_type: orm, group: "Contabilidad Domestica", label: "Entidad / Banco"}        
        arguments:    [null, Weo\BancoBundle\Entity\EntidadBanco, WeoBancoBundle:EntidadBancoAdmin]  
    weo.bancobundle.admin.cuenta:
        class: Weo\BancoBundle\Admin\CuentaAdmin
        tags:
            - { name: sonata.admin, manager_type: orm, group: "Contabilidad Domestica", label: "Cuentas" }
        arguments: [null, Weo\BancoBundle\Entity\Cuenta, WeoBancoBundle:CuentaAdmin]
    weo.bancobundle.admin.apunte:
        class: Weo\BancoBundle\Admin\ApunteAdmin
        tags:
            - { name: sonata.admin, manager_type: orm, group: "Contabilidad Domestica", label: Apunte }
        arguments: [null, Weo\BancoBundle\Entity\Apunte, WeoBancoBundle:ApunteAdmin]
    weo.bancobundle.admin.categoriaapunte:
        class: Weo\BancoBundle\Admin\CategoriaApunteAdmin
        tags:
            - { name: sonata.admin, manager_type: orm, group: "Contabilidad Domestica", label: "Categoria apunte" }
        arguments: [null, Weo\BancoBundle\Entity\CategoriaApunte, WeoBancoBundle:CategoriaApunteAdmin]
    weo.bancobundle.admin.oficinaentidad:
        class: Weo\BancoBundle\Admin\OficinaEntidadAdmin
        tags:
            - { name: sonata.admin, manager_type: orm, group: "Contabilidad Domestica", label: "Oficina" }
        arguments: [null, Weo\BancoBundle\Entity\OficinaEntidad, WeoBancoBundle:OficinaEntidadAdmin]

        
jms_security_extra:
    secure_controllers:  true
    secure_all_services: false        
        