<?php

namespace Application\Migrations;

use Doctrine\DBAL\Migrations\AbstractMigration,
    Doctrine\DBAL\Schema\Schema;

/**
 * Auto-generated Migration: Please modify to your need!
 */
class Version20120201231054 extends AbstractMigration
{
    public function up(Schema $schema)
    {
        // this up() migration is autogenerated, please modify it to your needs
        $this->abortIf($this->connection->getDatabasePlatform()->getName() != "mysql");
        
        $this->addSql("CREATE TABLE apunte (id INT AUTO_INCREMENT NOT NULL, tipo_apunte_id INT DEFAULT NULL, categoria_apunte_id INT DEFAULT NULL, cuenta_id INT DEFAULT NULL, concepto LONGTEXT NOT NULL, fecha_apunte DATETIME NOT NULL, INDEX IDX_E39B0232F62B632D (tipo_apunte_id), INDEX IDX_E39B02329C3A0E6 (categoria_apunte_id), INDEX IDX_E39B02329AEFF118 (cuenta_id), PRIMARY KEY(id)) ENGINE = InnoDB");
        $this->addSql("CREATE TABLE categoria_apunte (id INT AUTO_INCREMENT NOT NULL, nombre VARCHAR(500) NOT NULL, PRIMARY KEY(id)) ENGINE = InnoDB");
        $this->addSql("CREATE TABLE cuenta (id INT AUTO_INCREMENT NOT NULL, tipo_cuenta_id INT DEFAULT NULL, entidad_id INT DEFAULT NULL, nombre VARCHAR(100) NOT NULL, usuario_id INT NOT NULL, compartida TINYINT(1) NOT NULL, numero_cuenta VARCHAR(20) NOT NULL, INDEX IDX_31C7BFCF78814E56 (tipo_cuenta_id), INDEX IDX_31C7BFCF6CA204EF (entidad_id), PRIMARY KEY(id)) ENGINE = InnoDB");
        $this->addSql("CREATE TABLE entidad_banco (id INT AUTO_INCREMENT NOT NULL, nombre VARCHAR(100) NOT NULL, codigo_entidad VARCHAR(4) NOT NULL, PRIMARY KEY(id)) ENGINE = InnoDB");
        $this->addSql("CREATE TABLE oficina_entidad (id INT AUTO_INCREMENT NOT NULL, entidad_id INT DEFAULT NULL, nombre VARCHAR(100) NOT NULL, direccion TEXT NOT NULL, lat VARCHAR(100) NOT NULL, lon VARCHAR(100) NOT NULL, nombre_contacto VARCHAR(255) NOT NULL, email_contacto VARCHAR(255) NOT NULL, telefono VARCHAR(100) NOT NULL, codigo_oficina VARCHAR(4) NOT NULL, INDEX IDX_9892A80E6CA204EF (entidad_id), PRIMARY KEY(id)) ENGINE = InnoDB");
        $this->addSql("CREATE TABLE tipo_apunte (id INT AUTO_INCREMENT NOT NULL, nombre VARCHAR(500) NOT NULL, PRIMARY KEY(id)) ENGINE = InnoDB");
        $this->addSql("CREATE TABLE tipo_cuenta (id INT AUTO_INCREMENT NOT NULL, nombre VARCHAR(500) NOT NULL, PRIMARY KEY(id)) ENGINE = InnoDB");
        $this->addSql("ALTER TABLE apunte ADD CONSTRAINT FK_E39B0232F62B632D FOREIGN KEY (tipo_apunte_id) REFERENCES tipo_apunte(id)");
        $this->addSql("ALTER TABLE apunte ADD CONSTRAINT FK_E39B02329C3A0E6 FOREIGN KEY (categoria_apunte_id) REFERENCES categoria_apunte(id)");
        $this->addSql("ALTER TABLE apunte ADD CONSTRAINT FK_E39B02329AEFF118 FOREIGN KEY (cuenta_id) REFERENCES cuenta(id)");
        $this->addSql("ALTER TABLE cuenta ADD CONSTRAINT FK_31C7BFCF78814E56 FOREIGN KEY (tipo_cuenta_id) REFERENCES tipo_cuenta(id)");
        $this->addSql("ALTER TABLE cuenta ADD CONSTRAINT FK_31C7BFCF6CA204EF FOREIGN KEY (entidad_id) REFERENCES oficina_entidad(id)");
        $this->addSql("ALTER TABLE oficina_entidad ADD CONSTRAINT FK_9892A80E6CA204EF FOREIGN KEY (entidad_id) REFERENCES entidad_banco(id)");
    }

    public function down(Schema $schema)
    {
        // this down() migration is autogenerated, please modify it to your needs
        $this->abortIf($this->connection->getDatabasePlatform()->getName() != "mysql");
        
        $this->addSql("ALTER TABLE apunte DROP FOREIGN KEY FK_E39B02329C3A0E6");
        $this->addSql("ALTER TABLE apunte DROP FOREIGN KEY FK_E39B02329AEFF118");
        $this->addSql("ALTER TABLE oficina_entidad DROP FOREIGN KEY FK_9892A80E6CA204EF");
        $this->addSql("ALTER TABLE cuenta DROP FOREIGN KEY FK_31C7BFCF6CA204EF");
        $this->addSql("ALTER TABLE apunte DROP FOREIGN KEY FK_E39B0232F62B632D");
        $this->addSql("ALTER TABLE cuenta DROP FOREIGN KEY FK_31C7BFCF78814E56");
        $this->addSql("DROP TABLE apunte");
        $this->addSql("DROP TABLE categoria_apunte");
        $this->addSql("DROP TABLE cuenta");
        $this->addSql("DROP TABLE entidad_banco");
        $this->addSql("DROP TABLE oficina_entidad");
        $this->addSql("DROP TABLE tipo_apunte");
        $this->addSql("DROP TABLE tipo_cuenta");
    }
}
