<?php

namespace Application\Migrations;

use Doctrine\DBAL\Migrations\AbstractMigration,
    Doctrine\DBAL\Schema\Schema;

/**
 * Auto-generated Migration: Please modify to your need!
 */
class Version20120206232137 extends AbstractMigration
{
    public function up(Schema $schema)
    {
        // this up() migration is autogenerated, please modify it to your needs
        $this->abortIf($this->connection->getDatabasePlatform()->getName() != "mysql");
        
        $this->addSql("CREATE TABLE apunte_audit (id INT NOT NULL, rev INT NOT NULL, tipo_apunte_id INT DEFAULT NULL, categoria_apunte_id INT DEFAULT NULL, cuenta_id INT DEFAULT NULL, concepto LONGTEXT DEFAULT NULL, fecha_apunte DATETIME DEFAULT NULL, revtype VARCHAR(4) NOT NULL, PRIMARY KEY(id, rev)) ENGINE = InnoDB");
        $this->addSql("CREATE TABLE categoria_apunte_audit (id INT NOT NULL, rev INT NOT NULL, nombre VARCHAR(500) DEFAULT NULL, revtype VARCHAR(4) NOT NULL, PRIMARY KEY(id, rev)) ENGINE = InnoDB");
        $this->addSql("CREATE TABLE cuenta_audit (id INT NOT NULL, rev INT NOT NULL, tipo_cuenta_id INT DEFAULT NULL, entidad_id INT DEFAULT NULL, nombre VARCHAR(100) DEFAULT NULL, usuario_id INT DEFAULT NULL, compartida TINYINT(1) DEFAULT NULL, numero_cuenta VARCHAR(20) DEFAULT NULL, revtype VARCHAR(4) NOT NULL, PRIMARY KEY(id, rev)) ENGINE = InnoDB");
        $this->addSql("CREATE TABLE oficina_entidad_audit (id INT NOT NULL, rev INT NOT NULL, entidad_id INT DEFAULT NULL, nombre VARCHAR(100) DEFAULT NULL, direccion TEXT DEFAULT NULL, lat VARCHAR(100) DEFAULT NULL, lon VARCHAR(100) DEFAULT NULL, nombre_contacto VARCHAR(255) DEFAULT NULL, email_contacto VARCHAR(255) DEFAULT NULL, telefono VARCHAR(100) DEFAULT NULL, codigo_oficina VARCHAR(4) DEFAULT NULL, revtype VARCHAR(4) NOT NULL, PRIMARY KEY(id, rev)) ENGINE = InnoDB");
        $this->addSql("CREATE TABLE tipo_apunte_audit (id INT NOT NULL, rev INT NOT NULL, nombre VARCHAR(500) DEFAULT NULL, revtype VARCHAR(4) NOT NULL, PRIMARY KEY(id, rev)) ENGINE = InnoDB");
        $this->addSql("CREATE TABLE tipo_cuenta_audit (id INT NOT NULL, rev INT NOT NULL, nombre VARCHAR(500) DEFAULT NULL, revtype VARCHAR(4) NOT NULL, PRIMARY KEY(id, rev)) ENGINE = InnoDB");
    }

    public function down(Schema $schema)
    {
        // this down() migration is autogenerated, please modify it to your needs
        $this->abortIf($this->connection->getDatabasePlatform()->getName() != "mysql");
        
        $this->addSql("DROP TABLE apunte_audit");
        $this->addSql("DROP TABLE categoria_apunte_audit");
        $this->addSql("DROP TABLE cuenta_audit");
        $this->addSql("DROP TABLE oficina_entidad_audit");
        $this->addSql("DROP TABLE tipo_apunte_audit");
        $this->addSql("DROP TABLE tipo_cuenta_audit");
    }
}
